import asyncio
import base64
import json
import os
import random
import re
import logging
from typing import Dict, List, Sequence, Tuple

import requests

import numpy as np
from moviepy.editor import (
    AudioFileClip,
    CompositeVideoClip,
    ImageClip,
    VideoFileClip,
    concatenate_audioclips,
    concatenate_videoclips,
)
from moviepy.audio.AudioClip import AudioClip
from moviepy.video.fx import all as vfx
from openai import OpenAI
from PIL import Image, ImageDraw, ImageFont

from app.constants import FONT_CANDIDATES

logger = logging.getLogger(__name__)

# Basic look-and-feel for the autogenerated mini-scenes
VIDEO_SIZE: Tuple[int, int] = (1280, 720)
CLIP_DURATION = 4.5  # seconds per keyword scene
BACKGROUND_COLORS = [
    (34, 47, 62),
    (68, 189, 255),
    (243, 156, 18),
    (52, 152, 219),
    (72, 219, 151),
    (229, 80, 57),
]

SubtitleEntry = Tuple[Tuple[float, float], str]


def _pick_font(size: int) -> ImageFont.FreeTypeFont:
    """Try to load a reasonable TTF font; fall back to Pillow default."""
    for font_path, _ in FONT_CANDIDATES:
        if not os.path.exists(font_path):
            continue
        try:
            return ImageFont.truetype(font_path, size=size)
        except OSError:
            continue
    try:
        return ImageFont.truetype("Arial.ttf", size=size)
    except OSError:
        return ImageFont.load_default()


def _wrap_text(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.FreeTypeFont, max_width: int) -> List[str]:
    """Wrap text so it fits within the given width."""
    words = text.split()
    lines: List[str] = []
    current = ""

    for word in words:
        candidate = word if not current else f"{current} {word}"
        if draw.textlength(candidate, font=font) <= max_width:
            current = candidate
        else:
            if current:
                lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def _split_into_sentences(text: str) -> List[str]:
    """Lightweight sentence splitter for subtitles."""
    cleaned = text.strip()
    if not cleaned:
        return []
    parts = re.split(r"(?<=[.!?])\s+", cleaned)
    sentences = [p.strip() for p in parts if p.strip()]
    if not sentences and cleaned:
        sentences = [cleaned]
    return sentences


def _render_frame(keyword: str, caption: str) -> np.ndarray:
    """Render a single video frame (as numpy array) for one keyword scene."""
    bg_color = random.choice(BACKGROUND_COLORS)
    width, height = VIDEO_SIZE
    img = Image.new("RGB", (width, height), color=bg_color)
    draw = ImageDraw.Draw(img)

    title_font = _pick_font(72)
    body_font = _pick_font(44)

    # Title
    title_text = keyword.strip().title() or "Scene"
    title_width = draw.textlength(title_text, font=title_font)
    draw.text(
        ((width - title_width) / 2, 80),
        title_text,
        font=title_font,
        fill=(255, 255, 255),
    )

    # Caption block
    max_body_width = int(width * 0.75)
    wrapped = _wrap_text(draw, caption.strip(), body_font, max_body_width)
    y = height / 2 - (len(wrapped) * body_font.size * 1.2) / 2
    for line in wrapped:
        line_width = draw.textlength(line, font=body_font)
        draw.text(
            ((width - line_width) / 2, y),
            line,
            font=body_font,
            fill=(245, 245, 245),
        )
        y += body_font.size * 1.2

    return np.array(img)


def _parse_storyboard_response(raw: str, keywords: List[str]) -> List[Dict[str, str]]:
    """Try to turn model JSON output into a usable storyboard list."""
    try:
        data = json.loads(raw)
        if isinstance(data, dict):
            data = data.get("scenes") or data.get("items") or []
        if not isinstance(data, list):
            return []
    except json.JSONDecodeError:
        return []

    results: List[Dict[str, str]] = []
    for item in data:
        if not isinstance(item, dict):
            continue
        keyword = str(item.get("keyword") or "").strip()
        if not keyword and keywords:
            keyword = keywords[len(results) % len(keywords)]
        caption = str(
            item.get("caption")
            or item.get("description")
            or item.get("line")
            or keyword
        ).strip()
        if keyword:
            results.append({"keyword": keyword, "caption": caption})
    return results


async def _ask_storyboard(cli: OpenAI, keywords: List[str]) -> List[Dict[str, str]]:
    """Generate concise scene captions for the provided keywords via the LLM."""
    prompt = (
        "You craft ultra-short storyboard beats for a montage video. "
        "Return JSON only. Use this shape:\n"
        '[{"keyword": "...", "caption": "..."}].\n'
        "Each caption should be 1-2 short sentences (<=25 words) that evoke visuals "
        "for the keyword. Keep the tone energetic and helpful."
        f"\nKeywords: {', '.join(keywords)}"
    )

    def _run_request() -> List[Dict[str, str]]:
        response = cli.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {"role": "system", "content": "Return only JSON, no explanations."},
                {"role": "user", "content": prompt},
            ],
        )
        message = response.choices[0].message
        content = getattr(message, "content", None)
        if isinstance(message, dict):
            content = content or message.get("content", "")
        storyboard = _parse_storyboard_response(content or "", keywords)
        return storyboard

    return await asyncio.to_thread(_run_request)


def _render_storyboard(
    storyboard: List[Dict[str, str]],
    temp_dir: str,
    target_duration: float | None = None,
) -> Tuple[str, float]:
    """Render the storyboard slides into a single mp4."""
    if not storyboard:
        raise ValueError("Storyboard is empty")
    clips: List[ImageClip] = []
    total_duration = 0.0
    silence: AudioClip | None = None
    try:
        clip_duration = CLIP_DURATION
        if target_duration and target_duration > 0:
            clip_duration = max(target_duration / len(storyboard), 0.6)

        for scene in storyboard:
            frame = _render_frame(scene["keyword"], scene["caption"])
            clip = ImageClip(frame).set_duration(clip_duration)
            fade = min(0.25, clip_duration / 4)
            clip = clip.fx(vfx.fadein, fade).fx(vfx.fadeout, fade)
            clips.append(clip)
            total_duration += clip.duration

        final_clip = concatenate_videoclips(clips, method="compose")
        silence = AudioClip(lambda t: 0.0, duration=total_duration, fps=44_100)
        final_clip = final_clip.set_audio(silence)
        output_path = os.path.join(temp_dir, "keywords_video.mp4")
        final_clip.write_videofile(
            output_path,
            fps=24,
            codec="libx264",
            audio=True,
            audio_codec="aac",
            verbose=False,
            logger=None,
        )
        final_clip.close()
        if silence:
            silence.close()
            silence = None
        return output_path, total_duration
    finally:
        for clip in clips:
            clip.close()
        if silence:
            silence.close()


async def generate_keyword_video(
    cli: OpenAI,
    keywords: List[str],
    temp_dir: str,
    target_duration: float | None = None,
) -> Tuple[str, float]:
    """
    Build a stitched video where each keyword becomes a short slide.

    Returns (output_path, total_duration_seconds).
    """
    storyboard = await _ask_storyboard(cli, keywords)
    if not storyboard:
        storyboard = [{"keyword": kw, "caption": f"Quick beat about {kw}."} for kw in keywords]

    return await asyncio.to_thread(_render_storyboard, storyboard, temp_dir, target_duration)


async def extract_keywords(cli: OpenAI, text: str, max_keywords: int = 8) -> List[str]:
    """Ask the LLM to pull out the most important keywords/phrases."""
    def _run_request() -> List[str]:
        response = cli.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {
                    "role": "system",
                    "content": (
                        "Extract the most important keywords or short noun phrases. "
                        "Return JSON array only, e.g. [\"solar energy\", \"grid storage\"]."
                    ),
                },
                {
                    "role": "user",
                    "content": (
                        f"Text:\n{text}\n\n"
                        f"Return up to {max_keywords} keywords."
                    ),
                },
            ],
        )
        message = response.choices[0].message
        content = getattr(message, "content", None)
        if isinstance(message, dict):
            content = content or message.get("content", "")

        try:
            data = json.loads(content or "[]")
            if isinstance(data, dict):
                data = data.get("keywords") or data.get("items") or data.get("list") or []
            if not isinstance(data, list):
                return []
            keywords = [
                str(item).strip()
                for item in data
                if str(item).strip()
            ]
            return keywords[:max_keywords]
        except json.JSONDecodeError:
            return []

    return await asyncio.to_thread(_run_request)


async def generate_images_for_keywords(
    prompts: List[str],
    temp_dir: str,
    size: str = "1280x720",
    cli: OpenAI | None = None,
) -> List[str]:
    """
    Generate one image per prompt using a free, unauthenticated image prompt service.

    Uses pollinations.ai which does not require an API key. This keeps costs at zero but
    relies on external availability.
    """
    os.makedirs(temp_dir, exist_ok=True)
    paths: List[str] = []
    base_url = "https://image.pollinations.ai/prompt/"
    openai_allowed = cli is not None

    def _download_image(idx: int, prompt: str) -> str:
        url = f"{base_url}{requests.utils.quote(prompt)}?width={size.split('x')[0]}&height={size.split('x')[1]}"
        response = requests.get(url, timeout=60)
        if response.status_code >= 400:
            raise RuntimeError(f"Image fetch failed {response.status_code}: {response.text}")
        path = os.path.join(temp_dir, f"kw_{idx}.png")
        with open(path, "wb") as f:
            f.write(response.content)
        return path

    def _generate_image_with_openai(idx: int, prompt: str) -> str:
        if cli is None:
            raise RuntimeError("OpenAI client not provided for fallback image generation.")
        response = cli.images.generate(
            model="gpt-image-1",
            prompt=prompt,
            size="1024x1024",
        )
        data = getattr(response, "data", None)
        if not data:
            raise RuntimeError("OpenAI image response missing data.")
        b64 = getattr(data[0], "b64_json", None) if len(data) > 0 else None
        if not b64:
            raise RuntimeError("OpenAI image response missing b64_json.")
        img_bytes = base64.b64decode(b64)
        path = os.path.join(temp_dir, f"kw_openai_{idx}.png")
        with open(path, "wb") as f:
            f.write(img_bytes)
        return path

    for idx, prompt in enumerate(prompts):
        full_prompt = f"Cinematic illustration: {prompt}. Coherent subject, natural lighting, high detail, 16:9"
        path: str | None = None
        try:
            path = await asyncio.to_thread(_download_image, idx, full_prompt)
        except Exception as exc:  # noqa: BLE001
            logger.warning("Pollinations image failed for idx %s: %s", idx, exc)
            if cli is not None and openai_allowed:
                try:
                    path = await asyncio.to_thread(_generate_image_with_openai, idx, full_prompt)
                except Exception as openai_exc:  # noqa: BLE001
                    logger.warning("OpenAI image failed for idx %s: %s", idx, openai_exc)
                    if "403" in str(openai_exc) or "Forbidden" in str(openai_exc):
                        openai_allowed = False
        if path:
            paths.append(path)

    return paths


def text_to_scenes(text: str, max_scenes: int = 30) -> List[str]:
    """
    Slice full text into scene prompts (sentences or chunks). No keyword extraction used.
    """
    # Split by sentence enders; fallback to word chunks if needed.
    raw_parts = re.split(r"[.!?]\s+", text.strip())
    parts = [p.strip() for p in raw_parts if len(p.strip().split()) >= 4]
    if not parts:
        words = text.split()
        chunk_size = 20
        for i in range(0, len(words), chunk_size):
            chunk = " ".join(words[i : i + chunk_size]).strip()
            if len(chunk.split()) >= 4:
                parts.append(chunk)
    return parts[:max_scenes]


def build_subtitle_entries(text: str, total_duration: float, lead_time: float = 0.0) -> List[SubtitleEntry]:
    """Create timed subtitle entries spread across the provided duration."""
    if total_duration <= 0:
        return []

    sentences = _split_into_sentences(text)
    if not sentences:
        return []

    word_counts = [max(len(re.findall(r"\w+", sentence)), 1) for sentence in sentences]
    total_words = sum(word_counts) or 1
    entries: List[SubtitleEntry] = []
    cursor = 0.0
    remaining_duration = total_duration
    remaining_words = total_words

    for idx, (sentence, word_count) in enumerate(zip(sentences, word_counts)):
        if remaining_duration <= 0:
            break
        proportion = word_count / remaining_words if remaining_words else 1.0 / max(len(sentences) - idx, 1)
        span = max(remaining_duration * proportion, 0.75)
        if idx == len(sentences) - 1:
            span = remaining_duration
        else:
            span = min(span, remaining_duration)
        start = max(cursor - max(lead_time, 0.0), 0.0)
        end = start + span
        entries.append(((start, end), sentence))
        cursor = end + max(lead_time, 0.0)
        remaining_duration -= span
        remaining_words -= word_count

    if entries:
        last_start, _ = entries[-1][0]
        entries[-1] = ((last_start, total_duration), entries[-1][1])
    return entries


async def build_video_from_images(
    image_paths: List[str],
    temp_dir: str,
    duration_per_image: float = 4.5,
    target_duration: float | None = None,
) -> Tuple[str, float, int, int]:
    """Stitch provided images into a simple slideshow video with a silent audio track."""
    if not image_paths:
        raise ValueError("No images to build a video.")

    clips: List[ImageClip] = []
    total_duration = 0.0
    w, h = VIDEO_SIZE
    silence: AudioClip | None = None
    try:
        if target_duration and target_duration > 0 and image_paths:
            duration_per_image = target_duration / len(image_paths)

        for idx, path in enumerate(image_paths):
            clip = ImageClip(path).set_duration(duration_per_image)
            fade = min(0.25, duration_per_image / 4)
            clip = clip.fx(vfx.fadein, fade).fx(vfx.fadeout, fade)
            if idx == 0 and hasattr(clip, "size"):
                w, h = clip.size
            clips.append(clip)
            total_duration += clip.duration

        final_clip = concatenate_videoclips(clips, method="compose")
        silence = AudioClip(lambda t: 0.0, duration=total_duration, fps=44_100)
        final_clip = final_clip.set_audio(silence)
        output_path = os.path.join(temp_dir, "keywords_images_video.mp4")
        final_clip.write_videofile(
            output_path,
            fps=24,
            codec="libx264",
            audio=True,
            audio_codec="aac",
            verbose=False,
            logger=None,
        )
        final_clip.close()
        if silence:
            silence.close()
            silence = None
        return output_path, total_duration, w, h
    finally:
        for clip in clips:
            clip.close()
        if silence:
            silence.close()


async def synthesize_speech_from_text(
    cli: OpenAI,
    text: str,
    temp_dir: str,
    voice: str = "alloy",
    max_chars: int = 3800,
    ) -> Tuple[str, float]:
    """Generate mp3 narration from the provided text via OpenAI TTS."""
    if not text.strip():
        raise ValueError("Text is empty; cannot synthesize speech.")

    trimmed_text = text.strip().replace("[PAUSE]", "<break time='3s'/>")
    if len(trimmed_text) > max_chars:
        trimmed_text = trimmed_text[: max_chars - 20] + "..."

    os.makedirs(temp_dir, exist_ok=True)
    audio_path = os.path.join(temp_dir, "keywords_narration.mp3")

    def _synthesize() -> Tuple[str, float]:
        response = cli.audio.speech.create(
            model="tts-1-hd",
            voice=voice,
            input=trimmed_text,
            response_format="mp3",
        )

        if hasattr(response, "stream_to_file"):
            response.stream_to_file(audio_path)
        else:
            with open(audio_path, "wb") as f:
                if hasattr(response, "iter_bytes"):
                    for chunk in response.iter_bytes():
                        f.write(chunk)
                elif hasattr(response, "read"):
                    f.write(response.read())
                else:
                    raise RuntimeError("TTS response missing audio bytes.")

        audio_clip = AudioFileClip(audio_path)
        duration = audio_clip.duration
        audio_clip.close()
        return audio_path, duration

    return await asyncio.to_thread(_synthesize)


async def ensure_text_for_duration(
    cli: OpenAI,
    text: str,
    target_duration: float,
    target_wpm: int = 150,
    max_chars: int = 3600,
    pause_every: float | None = None,
    pause_seconds: float = 3.0,
) -> str:
    """
    If the text is too short for the target duration, expand/paraphrase it to fill the time.
    """
    if target_duration <= 0:
        return text

    words = text.split()
    needed_words = int(target_duration / 60.0 * target_wpm)
    if len(words) >= int(needed_words * 0.9):
        return text

    pause_note = ""
    if pause_every and pause_every > 0 and pause_seconds > 0:
        pause_note = (
            f"\nInsert a short natural pause marker like '[PAUSE]' every ~{int(pause_every)} seconds "
            f"of narration (about every {int(pause_every/60*target_wpm)} words). "
            "Keep prose flowing; no bullet lists."
        )

    prompt = (
        "You are expanding a script for narration. Keep the meaning and tone, but elaborate with helpful detail "
        f"so the length is about {needed_words} words. Keep it coherent prose, no lists."
        f"{pause_note}"
        f"\n\nOriginal text:\n{text}"
    )

    def _expand() -> str:
        response = cli.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[
                {"role": "system", "content": "Return only the expanded script text."},
                {"role": "user", "content": prompt},
            ],
        )
        message = response.choices[0].message
        content = getattr(message, "content", None)
        if not content and isinstance(message, dict):
            content = message.get("content", "")
        return (content or "").strip()

    expanded = await asyncio.to_thread(_expand)
    final_text = expanded or text
    if len(final_text) > max_chars:
        final_text = final_text[: max_chars - 20] + "..."
    return final_text


async def stretch_audio_to_duration(
    source_path: str,
    target_duration: float,
    temp_dir: str,
    max_factor: float = 1.8,
) -> Tuple[str, float]:
    """
    Time-stretch the audio so it matches target_duration.

    Returns the path to the stretched audio and its duration.
    """
    if target_duration <= 0:
        raise ValueError("target_duration must be positive for time-stretching.")

    audio_clip = AudioFileClip(source_path)
    try:
        current = audio_clip.duration or 0.0
        if current <= 0:
            raise ValueError("Audio duration is zero; cannot stretch.")

        # Only speed up (never slow down) to avoid unnatural audio; pad with silence later if shorter.
        if current <= target_duration * 1.02:
            return source_path, current

        factor = current / target_duration
        factor = min(max(factor, 1.0), max_factor)
        stretched = audio_clip.fx(vfx.speedx, factor=factor)
        stretched_path = os.path.join(temp_dir, "keywords_narration_stretched.mp3")
        stretched.write_audiofile(
            stretched_path,
            codec="libmp3lame",
            bitrate="128k",
            fps=44_100,
            logger=None,
        )
        stretched.close()

        stretched_clip = AudioFileClip(stretched_path)
        duration = stretched_clip.duration
        stretched_clip.close()
        return stretched_path, duration
    finally:
        audio_clip.close()


def _render_subtitle_clip(entry: SubtitleEntry, video_size: Tuple[int, int]) -> ImageClip | None:
    """Turn a subtitle entry into an overlay clip."""
    (start, end), text = entry
    duration = max(end - start, 0.0)
    if duration <= 0:
        return None

    width, height = video_size
    overlay_height = int(height * 0.18)
    img = Image.new("RGBA", (width, overlay_height), (0, 0, 0, 0))
    draw = ImageDraw.Draw(img, "RGBA")
    padding = 24
    draw.rectangle(
        (
            padding,
            padding // 2,
            width - padding,
            overlay_height - padding // 2,
        ),
        fill=(0, 0, 0, 170),
    )

    font = _pick_font(32)
    lines = _wrap_text(draw, text, font, width - padding * 2)
    if len(lines) > 2:
        lines = lines[:2]
        lines[-1] = lines[-1].rstrip(".!,;:") + "..."

    y = overlay_height / 2 - (len(lines) * font.size * 1.3) / 2
    for line in lines:
        line_width = draw.textlength(line, font=font)
        draw.text(
            ((width - line_width) / 2, y),
            line,
            font=font,
            fill=(255, 255, 255, 255),
        )
        y += font.size * 1.3

    rgba = np.array(img)
    rgb = rgba[..., :3]
    alpha = rgba[..., 3] / 255.0

    clip = ImageClip(rgb).set_start(start).set_duration(duration)
    mask = ImageClip(alpha, ismask=True).set_start(start).set_duration(duration)
    clip = clip.set_mask(mask)
    clip = clip.set_position(("center", height - overlay_height - 30))
    return clip


def _subtitle_clips_from_entries(
    subtitles: Sequence[SubtitleEntry],
    video_size: Tuple[int, int],
) -> List[ImageClip]:
    clips: List[ImageClip] = []
    for entry in subtitles:
        clip = _render_subtitle_clip(entry, video_size)
        if clip is not None:
            clips.append(clip)
    return clips


async def mux_video_audio_and_subtitles(
    video_path: str,
    audio_path: str,
    subtitles: Sequence[SubtitleEntry],
    temp_dir: str,
    target_duration: float | None = None,
) -> Tuple[str, float, int, int]:
    """
    Combine the base video with narration audio and burned-in subtitles.

    Returns output_path, final_duration, width, height.
    """
    def _mux() -> Tuple[str, float, int, int]:
        video_clip = VideoFileClip(video_path)
        audio_clip = AudioFileClip(audio_path)

        target = target_duration if target_duration and target_duration > 0 else max(
            video_clip.duration or 0.0,
            audio_clip.duration or 0.0,
        )
        if target <= 0:
            raise ValueError("Video or audio duration is zero.")

        if video_clip.duration < target:
            freeze = video_clip.to_ImageClip(t=max(video_clip.duration - 0.05, 0.0)).set_duration(
                target - video_clip.duration
            )
            freeze = freeze.set_start(video_clip.duration)
            extended = concatenate_videoclips([video_clip, freeze], method="compose")
            video_clip = extended
        elif video_clip.duration > target:
            video_clip = video_clip.subclip(0, target)
        else:
            video_clip = video_clip.set_duration(target)

        audio_for_video = audio_clip
        silence = None
        if audio_clip.duration < target - 0.1:
            silence_duration = target - audio_clip.duration
            silence = AudioClip(lambda t: 0.0, duration=silence_duration, fps=getattr(audio_clip, "fps", 44_100))
            audio_for_video = concatenate_audioclips([audio_clip, silence])
        elif audio_clip.duration > target:
            audio_for_video = audio_clip.subclip(0, target)

        video_with_audio = video_clip.set_audio(audio_for_video)
        subtitle_clips = _subtitle_clips_from_entries(subtitles, video_with_audio.size)
        layers = [video_with_audio, *subtitle_clips] if subtitle_clips else [video_with_audio]

        final_clip = CompositeVideoClip(layers)
        output_path = os.path.join(temp_dir, "keywords_video_final.mp4")
        final_clip.write_videofile(
            output_path,
            fps=24,
            codec="libx264",
            audio=True,
            audio_codec="aac",
            verbose=False,
            logger=None,
        )
        duration = final_clip.duration
        width, height = final_clip.size

        final_clip.close()
        video_with_audio.close()
        video_clip.close()
        if audio_for_video is not audio_clip:
            audio_for_video.close()
        audio_clip.close()
        if silence:
            silence.close()
        for clip in subtitle_clips:
            clip.close()

        return output_path, duration, width, height

    return await asyncio.to_thread(_mux)
